import React, { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "id" | "en";

interface LanguageContextValue {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (path: string, defaultValue?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const translations = {
  id: {
    common: {
      home: "Beranda",
      plan: "Rencana",
      history: "Riwayat",
      wallet: "Dompet",
      settings: "Pengaturan",
      logout: "Keluar",
      cancel: "Batal",
      save: "Simpan",
      confirm: "Konfirmasi",
      edit: "Ubah",
      delete: "Hapus",
      loading: "Memproses...",
      success: "Berhasil",
      error: "Gagal",
      account: "Akun & Pengaturan",
      back: "Kembali",
      next: "Lanjut",
      skip: "Lewati",
      done: "Selesai",
      close: "Tutup",
      add: "Tambah Baru",
      record: "Catat",
      today: "Hari Ini",
      total: "Total",
      estimated: "Estimasi",
      notes: "Catatan",
      actions: "Aksi",
      saveChanges: "Simpan Perubahan",
    },
    settings: {
      title: "Pengaturan",
      subtitle: "Biar app ini terasa makin pas dengan ritmemu.",
      description: "Atur preferensi akun, izin notifikasi, dan kelola ekspor data di sini.",
      accountSection: "Akun",
      accountDesc: "Akun Budget Flow",
      changePassword: "Ganti Password",
      changePasswordDesc: "Ubah password buat keamanan tambahan.",
      changePasswordButton: "Buka",
      logoutDesc: "Keluar dari akun ini kapan saja.",
      logoutButton: "Keluar",
      deleteAccount: "Hapus Akun",
      deleteAccountDesc: "Hapus permanen seluruh data dan akunmu dari database.",
      deleteAccountButton: "Hapus",
      preferencesSection: "Preferensi",
      browserNotifications: "Notifikasi Browser",
      browserNotificationsActive: "Aktif – kamu bakal dapat pengingat budget & tagihan rutin.",
      browserNotificationsBlocked: "Diblokir – aktifkan di pengaturan browser (klik 🔒 di address bar).",
      browserNotificationsDefault: "Izinkan agar dapat pengingat budget & tagihan rutin.",
      browserNotificationsUnsupported: "Browser ini gak mendukung notifikasi.",
      browserNotificationsBtn: "Aktifkan",
      androidTracking: "Pemantauan Transaksi Android",
      androidTrackingActive: "Akses aktif – transaksi otomatis dipantau di background dari notifikasi/email.",
      androidTrackingInactive: "Akses mati – aktifkan biar app bisa mencatat otomatis dari GoPay, SeaBank, dan Gmail.",
      androidTrackingBtnActive: "Atur",
      androidTrackingBtnInactive: "Aktifkan",
      testNotification: "Tes Kirim Notifikasi",
      testNotificationDesc: "Ketuk buat tes apakah notifikasi push sistem berfungsi.",
      testNotificationBtn: "Tes",
      designPreview: "Design Preview (V2)",
      designPreviewDesc: "Coba antarmuka baru dengan tema Dark Hybrid modern.",
      designPreviewBtn: "Buka V2",
      viewTutorial: "Lihat Tutorial Lagi",
      viewTutorialDesc: "Buka onboarding lagi dan munculkan starter checklist.",
      viewTutorialBtn: "Buka",
      appPermissions: "Daftar Izin Aplikasi",
      appPermissionsDesc: "Aplikasi keuangan yang dipantau notifikasinya. OTP dan kode verifikasi selalu difilter otomatis.",
      appPermissionsFooter: "Aktif saat Budget Flow berjalan sebagai APK Android.",
      financialData: "Data Keuangan",
      exportCSV: "Ekspor Transaksi (CSV)",
      exportCSVDesc: "Unduh salinan transaksi buat dibagikan atau dicek lagi.",
      exportCSVBtn: "Ekspor",
      aboutApp: "Tentang Aplikasi",
      appVersion: "Versi Aplikasi",
      language: "Bahasa Aplikasi",
      languageDesc: "Ganti bahasa antarmuka aplikasi.",
      languageIndo: "Bahasa Indonesia",
      languageEng: "English",
      modalChangePasswordTitle: "Ganti Password",
      modalChangePasswordSub: "Buat password baru yang aman untuk akunmu",
      modalNewPasswordLabel: "Password Baru",
      modalNewPasswordPlaceholder: "Minimal 6 karakter",
      modalConfirmPasswordLabel: "Konfirmasi Password Baru",
      modalConfirmPasswordPlaceholder: "Ulangi password baru",
      modalLogoutTitle: "Keluar dari Akun?",
      modalLogoutDesc: "Yakin mau keluar? Kamu harus masuk lagi buat mengakses data pencatatan transaksimu.",
      modalLogoutConfirm: "Keluar Sekarang",
      modalDeleteTitle: "Hapus Akun Permanen?",
      modalDeleteDesc: "Yakin mau hapus akunmu? Seluruh kategori, dompet, transaksi, dan data lainnya bakal dihapus permanen dari database dan gak bisa dikembalikan.",
      modalDeleteConfirm: "Hapus Permanen",
    },
    home: {
      dailySpending: "RINGKASAN KEUANGAN",
      safeToSpendToday: "SAFE-TO-SPEND HARI INI",
      safeToSpendDesc: "Sisa budget jajan aman hari ini biar gak mengganggu tabungan atau tagihan bulananmu.",
      cleanCash: "DANA BERSIH",
      upcomingBills: "TAGIHAN MENDATANG",
      daysToPayday: "HARI KE GAJIAN",
      daysToPaydaySuffix: "hari",
      dailyLimit: "PEMAKAIAN HARIAN",
      dailyLimitOver: "LEWAT BATAS!",
      dailyLimitNormal: "Batas aman harian: Rp {limit}",
      overspendMessage: "Lewat batas Rp {amount}! Kurangi jajan besok dan cek pengeluaranmu hari ini.",
      progressPlan: "PROGRESS RENCANA BULAN NAMA",
      planIncome: "Estimasi Pemasukan",
      planExpense: "Total Pengeluaran",
      planSavings: "Sisa Rencana",
      categorySpending: "Pemakaian Budget Rencana",
      todayTransactions: "PENGELUARAN HARI INI",
      noTransactionsToday: "Belum ada pengeluaran hari ini. Yuk catat dengan ketuk tombol + di bawah!",
      checklistTitle: "Starter Checklist",
      checklistSubtitle: "Selesaikan langkah awal berikut biar pantau Safe-To-Spend harianmu makin akurat.",
      checklistIntro: "Langkah Pengenalan",
      checklistDismissSuccess: "Starter Checklist berhasil disembunyikan. Kamu bisa aktifkan lagi lewat Pengaturan.",
      checklistAllDone: "Keren! Semua langkah awal keuanganmu sudah beres.",
      checklistNotDone: "Selesaikan langkah awal berikut biar pantau Safe-To-Spend harianmu makin akurat.",
      checklistProgress: "Progres Setup",
      checklistCompletedPercent: "{percent}% Selesai",
      checklistDismissTooltip: "Sembunyikan Checklist",
      step1Title: "Sambungkan Dompet Pertama",
      step1Desc: "Masukkan bank, e-wallet, atau uang tunai buat pantau saldomu.",
      step1Action: "Tambah Dompet",
      step2Title: "Atur Rencana Pemasukan",
      step2Desc: "Tulis estimasi gaji atau uang bulanan yang masuk.",
      step2Action: "Atur Pemasukan",
      step3Title: "Set Anggaran Kategori",
      step3Desc: "Buat alokasi jajan maksimal per kategori (misal: Makanan, Transport).",
      step3Action: "Atur Budget",
      step4Title: "Catat Transaksi Pertama",
      step4Desc: "Mulai catat pengeluaran harianmu, bisa manual atau otomatis.",
      step4Action: "Catat Sekarang",
      step5Title: "Koreksi & Cocokkan Saldo",
      step5Desc: "Sesuaikan saldo awal biar pas dengan kondisi uang aslimu.",
      step5Action: "Update Saldo",
      checklistDone: "Selesai",
      overview: "Ringkasan",
      analytics: "Analisis",
      safeToSpendLeft: "Kamu masih punya sisa Rp {amount} budget jajan hari ini.",
      spent: "terpakai",
      paydayModalTitle: "Ubah Tanggal Gajian",
      paydayModalSub: "Atur tanggal gajian biar siklus Safe-To-Spend harianmu pas.",
      paydayLabel: "Tanggal Gajian (1 - 31)",
      paydayDesc: "Sisa budget jajan aman harian (Safe-To-Spend) bakal dihitung ulang berdasarkan sisa hari sampai tanggal gajian ini.",
      paydayError: "Tanggal gajian harus di antara tanggal 1 sampai 31.",
      paydaySuccess: "Tanggal gajian berhasil diubah ke tanggal {day} setiap bulan.",
      loadingDashboard: "Memuat Dashboard...",
      dashboardError: "Gagal memuat data dashboard.",
      permissionTitle: "Nyalakan Auto-Track Transaksi",
      permissionDesc: "Biar praktis, Budget Flow butuh izin notifikasi buat catat pengeluaran dari SMS atau e-wallet secara otomatis.",
      permissionBtn: "Aktifkan Sekarang",
      permissionError: "Gagal membuka pengaturan.",
      avgDaily: "Rata-Rata Harian",
      totalTransactions: "Total Transaksi",
      planUsage: "Pemakaian Rencana",
      qrisFreq: "Frekuensi QRIS",
      times: "kali",
      dailySpendingTrend: "Tren Pengeluaran Harian",
      expenses: "Pengeluaran",
      day: "Hari",
      noTransactionsThisMonth: "Belum ada data transaksi bulan ini.",
      categorySpendingShare: "Porsi Pengeluaran Kategori",
      noCategorySpending: "Belum ada pengeluaran kategori.",
      topSpendingCategories: "Pengeluaran Terbesar",
      smartInsights: "Insight Pintar",
      qrisBurnRateTitle: "💡 QRIS Burn Rate:",
      qrisBurnRateText: "Pengeluaran paling deras berasal dari kategori {category}. Coba batasi QRIS e-wallet biar gak kebablasan.",
      qrisBurnRateEmpty: "Pola transaksi e-wallet belum bisa dianalisis. Coba impor atau catat transaksi dulu.",
      avgSpendingTitle: "📈 Rata-rata spending harian:",
      avgSpendingText: "per hari. Kalau konsisten di bawah Rp {limit}, kamu bisa hemat sampai Rp {savings} bulan ini!",
      quickActionsTitle: "Aksi Cepat",
      quickActionsSubtitle: "Menu cepat buat kelola catatan keuanganmu",
      actionUploadReceiptTitle: "Upload Struk Transaksi",
      actionUploadReceiptDesc: "Catat pengeluaran lewat foto/scan struk belanjaan",
      actionScreenshotBalanceTitle: "Update Saldo Screenshot",
      actionScreenshotBalanceDesc: "Koreksi nominal saldo e-wallet via gambar layar",
      actionImportCsvTitle: "Import CSV Transaksi",
      actionImportCsvDesc: "Unggah berkas riwayat transaksi bank sekaligus"
    },
    wallets: {
      firstRunWalletTitle: "Kelola Dompet Keuangan",
      firstRunWalletDesc: "Di menu Dompet ini, kamu bisa pantau uang tunai, rekening bank, atau e-wallet. Saldomu dibagi jadi Saldo Konfirmasi (angka pasti terakhir) dan Saldo Estimasi (pemakaian setelah konfirmasi terakhir).",
      title: "Daftar Dompet",
      subtitle: "Pantau saldo terkonfirmasi vs estimasi dari notifikasi otomatis.",
      addWallet: "Tambah Dompet",
      importStatement: "Impor Rekening",
      estimatedBalance: "Saldo Estimasi",
      confirmedBalance: "Saldo Konfirmasi",
      confirmedBalanceDesc: "Terakhir disinkronkan dari notifikasi/email transaksi.",
      daysAgo: "{days} hari lalu",
      justNow: "baru saja",
      needConfirmation: "Perlu Konfirmasi",
      gapDifference: "Selisih estimasi: Rp {gap}",
      resolveGap: "Selesaikan Gap",
      recentTransactions: "Transaksi Terakhir",
      noTransactions: "Belum ada transaksi di dompet ini.",
      importCSV: "Impor CSV",
      importCSVDesc: "Unggah mutasi rekening dari file CSV.",
      scanReceipt: "Pindai Struk (OCR)",
      scanReceiptDesc: "Ambil foto atau pilih gambar struk untuk pencatatan otomatis.",
      addWalletTitle: "Tambah Dompet Baru",
      walletName: "Nama Dompet",
      walletNamePlaceholder: "Contoh: BCA, GoPay, Tunai",
      walletInitialBalance: "Saldo Awal (Rp)",
      walletType: "Tipe Dompet",
      walletTypeBank: "Rekening Bank",
      walletTypeEWallet: "Dompet Digital (E-Wallet)",
      walletTypeCash: "Cash / Tunai",
      walletTypeOther: "Lainnya",
      saveWallet: "Simpan Rekening",
      scanReceiptTitle: "Pindai Struk AI OCR",
      scanReceiptSubtitle: "Pindai otomatis struk belanja untuk pencatatan instan",
      selectReceiptImage: "Pilih Foto Struk",
      processingOCR: "AI sedang membaca struk... Harap tunggu.",
      ocrResult: "Hasil Pindai Struk",
      ocrTotalAmount: "Total Terdeteksi",
      ocrMerchant: "Merchant Terdeteksi",
      ocrNote: "Catatan Otomatis",
      ocrAddToHistory: "Catat sebagai Pengeluaran",
      importCsvTitle: "Impor Mutasi Rekening (CSV)",
      importCsvSubtitle: "Pilih file CSV mutasi dari mobile banking Anda",
      selectCsvFile: "Pilih File CSV",
      importCsvColumns: "Sesuaikan Kolom CSV",
      importCsvBtn: "Mulai Impor",
      labelNeverConfirmed: "Belum pernah",
      btnGapAnalysis: "Analisis Gap",
      btnAdjustBalance: "Koreksi Saldo",
      btnRegisterNew: "Registrasi Wallet Baru",
      descRegisterNew: "Tambahkan bank atau e-wallet baru yang kamu miliki",
      formWalletName: "Nama Dompet",
      formWalletNamePlaceholder: "BCA Sakuku, GoPay, dll.",
      formWalletType: "Tipe Dompet",
      formProvider: "Provider (Opsional)",
      formProviderPlaceholder: "BCA, Mandiri, GoPay, OVO",
      formInitialBalance: "Saldo Awal (Rp)",
      btnSaving: "Menyimpan...",
      loadingWallets: "Memuat Daftar Dompet..."
    },
    budget: {
      headerTag: "Rencana Keuangan",
      title: "Rencana & Kategori",
      subtitle: "Atur alokasi budget, sumber pemasukan, dan tagihan rutinmu.",
      monthlyOverview: "Ringkasan Bulanan",
      totalPlanned: "Total Budget",
      totalSpent: "Total Terpakai",
      remainingPlanned: "Sisa Budget",
      addCategory: "Tambah Kategori",
      manageRecurring: "Kelola Recurring",
      statusHealthy: "Aman",
      statusWatch: "Waspada",
      statusOver: "Melebihi Batas",
      categoryName: "Nama Kategori",
      categoryBudget: "Anggaran Bulanan",
      recurringExpenses: "Tagihan Berulang (Recurring)",
      addRecurring: "Tambah Tagihan",
      recurringName: "Nama Tagihan",
      recurringAmount: "Nominal Tagihan",
      recurringPeriod: "Periode",
      recurringPeriodMonthly: "Bulanan",
      recurringPeriodWeekly: "Mingguan",
      recurringDueDate: "Jatuh Tempo",
      recurringDueDateSuffix: "setiap tanggal {date}",
      recurringAutoSync: "Sinkronisasi Otomatis",
      categoryManagement: "Kelola Kategori Anggaran",
      addCategoryTitle: "Tambah Kategori Anggaran",
      editCategoryTitle: "Edit Kategori Anggaran",
      saveCategory: "Simpan Kategori",
      deleteCategoryConfirm: "Apakah Anda yakin ingin menghapus kategori ini? Transaksi di kategori ini akan dipindahkan ke kategori 'Lainnya'.",
      tabCategory: "Budget Kategori",
      tabCategoryMobile: "Kategori",
      tabIncome: "Sumber Pemasukan",
      tabIncomeMobile: "Pemasukan",
      tabRecurring: "Tagihan Rutin",
      tabRecurringMobile: "Tagihan",
      utilization: "Total Pemakaian",
      statusOnTrack: "Sesuai Target",
      statusUnder: "Sisa Budget",
      recsTitle: "Rekomendasi",
      recsCollapse: "Ringkas",
      recsExpand: "Lihat semua",
      detailsTitle: "Detail Kategori",
      detailsDesc: "Bandingkan budget dan pemakaian per kategori belanja bulananmu.",
      activeCategories: "{count} kategori aktif",
      emptyCategoriesTitle: "Belum Ada Kategori Budget",
      emptyCategoriesDesc: "Tambahkan kategori pengeluaran bulanan (misal: Makanan, Hiburan) lengkap dengan anggarannya.",
      emptyCategoriesBtn: "Tambah Kategori Pertama",
      labelTransactionsCount: "{count} transaksi",
      labelBudget: "Budget",
      labelSpent: "Terpakai",
      labelRemaining: "Sisa",
      labelOver: "Lebih",
      incomeTitle: "Sumber Pemasukan",
      incomeDesc: "Atur daftar sumber pendapatan bulanan atau mingguanmu.",
      incomeAddBtn: "Tambah Pemasukan",
      incomeEmptyTitle: "Belum Ada Rencana Pemasukan",
      incomeEmptyDesc: "Tambahkan sumber pemasukan bulanan (gaji, bisnis, dll.) biar Safe-To-Spend kehitung akurat.",
      incomeEmptyBtn: "Tambah Pemasukan Pertama",
      recurringTitle: "Tagihan Rutin",
      recurringDesc: "{count} tagihan rutin terdaftar.",
      recurringSyncBtn: "Sinkronkan",
      recurringExportBtn: "Ekspor .ics",
      recurringAddBtn: "Tambah Tagihan",
      recurringEmptyTitle: "Belum Ada Tagihan Rutin",
      recurringEmptyDesc: "Tambahkan tagihan rutin bulanan (sewa kos, listrik, wifi) biar gak repot nyatat pengeluaran wajib.",
      recurringEmptyBtn: "Tambah Tagihan Pertama",
      recurringEveryDate: "Tiap Tanggal {day}",
      recurringEveryFreq: "Tiap {freq}",
      firstRunPlanTitle: "Kelola Anggaran Kategori Belanja",
      firstRunPlanDesc: "Di sini kamu membandingkan alokasi budget belanja bulanan dengan total pengeluaran riil per kategori. Kamu juga bakal dapat rekomendasi kalau pemakaianmu gak sesuai target.",
      firstRunIncomeTitle: "Rencana Pemasukan Rutin",
      firstRunIncomeDesc: "Di sini kamu bisa merencanakan estimasi pemasukan bulanan, mingguan, atau sekali waktu. Sumber pemasukan ini dipakai buat menghitung budget jajan aman (Safe-To-Spend) di Beranda.",
      firstRunRecurringTitle: "Daftar Tagihan Rutin",
      firstRunRecurringDesc: "Pantau tagihan tetap bulanan atau mingguan (seperti sewa kost, langganan internet, listrik). Kamu bisa menyinkronkan tagihan ini ke pengeluaran bulanan secara langsung dengan tombol Sinkronkan."
    },
    history: {
      headerTag: "Buku Kas",
      title: "Riwayat Transaksi",
      subtitle: "Lihat dan sesuaikan semua catatan pengeluaran & pemasukanmu.",
      searchPlaceholder: "Cari transaksi...",
      filterCategory: "Semua Kategori",
      filterWallet: "Semua Dompet",
      filterMonth: "Semua Bulan",
      noTransactions: "Tidak ada transaksi yang cocok dengan filter Anda.",
      totalExpenses: "Total Pengeluaran",
      totalIncome: "Total Pemasukan",
      transactionDetails: "Detail Transaksi",
      dateLabel: "Tanggal",
      amountLabel: "Nominal",
      categoryLabel: "Kategori",
      walletLabel: "Dompet / Rekening",
      noteLabel: "Catatan",
      deleteTransactionConfirm: "Yakin mau hapus transaksi ini?",
      emptyTitle: "Belum Ada Transaksi",
      emptyDesc: "Mulai catat pengeluaran atau pemasukan pertamamu biar riwayatnya muncul di sini.",
      emptyBtn: "Catat Transaksi Pertama",
      dateToday: "Hari Ini",
      dateYesterday: "Kemarin",
      txAutoNotif: "Notifikasi Otomatis",
      txManual: "Transaksi Manual",
      labelNotifDetail: "Detail Notifikasi:",
      labelNote: "Catatan:",
      noNote: "Gak ada catatan",
      btnEditNote: "Ubah",
      btnCancel: "Batal",
      btnSave: "Simpan",
      labelCategory: "Kategori:",
      btnSelectCategory: "+ Pilih Kategori",
      btnNoCategory: "— Tanpa Kategori —",
      btnDelete: "Hapus",
      loadingLedger: "Memuat Histori...",
      deleteConfirm: "Yakin mau hapus transaksi ini?",
      firstRunHistoryTitle: "Tinjau Riwayat Transaksi",
      firstRunHistoryDesc: "Menu Riwayat ini difokuskan penuh buat memantau pengeluaran/pemasukan yang udah terjadi. Di sini kamu bisa cari transaksi, kasih catatan tambahan, atau atur ulang kategori anggaran transaksi."
    },
    transactionModal: {
      expenseTitle: "Tambah Expense",
      incomeTitle: "Tambah Pemasukan",
      incomeEditTitle: "Edit Pemasukan",
      directionNewTx: "Transaksi Baru",
      labelAmount: "Nominal (Rp)",
      labelCategory: "Kategori",
      labelCategoryPlaceholder: "Pilih Kategori",
      labelWallet: "Dompet / Wallet (Opsional)",
      labelWalletStorage: "Dompet / Wallet (Penyimpanan)",
      labelWalletPlaceholder: "— Cash / Manual (Tanpa Wallet) —",
      labelDate: "Tanggal",
      labelDatePlaceholder: "Pilih Tanggal",
      labelNote: "Catatan / Note",
      labelNoteExpensePlaceholder: "Makan siang nasi goreng...",
      labelNoteIncomePlaceholder: "Gaji pokok bulan Mei...",
      btnSaveExpense: "Simpan Pengeluaran",
      btnSaveIncome: "Simpan Pemasukan",
      btnSaveChange: "Simpan Perubahan",
      msgInvalidAmount: "Nominal pengeluaran tidak valid.",
      msgInvalidAmountIncome: "Nominal pemasukan tidak valid.",
      msgSelectCategory: "Pilih kategori pengeluaran.",
      msgSelectSource: "Pilih sumber pemasukan.",
      msgSaveSuccessExpense: "Pengeluaran berhasil ditambahkan.",
      msgSaveSuccessIncome: "Pemasukan berhasil direkam.",
      msgSaveSuccessIncomeUpdate: "Pemasukan berhasil diperbarui.",
      newTransaction: "Transaksi Baru",
      addExpenseTitle: "Tambah Pengeluaran",
      addIncomeTitle: "Tambah Pemasukan",
      selectCategoryPlaceholder: "Pilih Kategori",
      manualCashNoWallet: "— Tunai / Manual (Tanpa Dompet) —",
      selectDatePlaceholder: "Pilih Tanggal",
      notePlaceholderExpense: "Makan siang, jajan kopi, dll...",
      notePlaceholderIncome: "Gaji pokok, bonus, dll...",
      btnSaving: "Menyimpan...",
      labelIncomeSource: "Sumber Pemasukan",
      selectSourcePlaceholder: "Pilih Sumber",
      labelWalletDeposit: "Dompet Penerima (Opsional)"
    },
    tour: {
      "welcome-home": {
        title: "Ini Beranda Kamu",
        body: "Pantau Safe-To-Spend (belanja aman hari ini), batas harian, dan ringkasan budget bulanan dari sini.",
        primaryCta: "Mulai Catat",
      },
      "open-record-sheet": {
        title: "Klik Tombol Catat",
        body: "Tekan tombol + di tengah navigasi ini (atau tombol 'Catat Baru' di sidebar) untuk membuka hub pencatatan transaksi keuangan Anda.",
      },
      "choose-expense": {
        title: "Pilih Pengeluaran",
        body: "Tekan tombol Pengeluaran untuk mencatat uang keluar secara manual.",
      },
      "input-amount": {
        title: "Masukkan Nominal",
        body: "Ketik nominal pengeluaran Anda pada kolom ini (contoh: 15.000).",
        primaryCta: "Lanjut",
      },
      "save-expense": {
        title: "Simpan Transaksi",
        body: "Ketik nominal belanja di atas, pilih kategori (opsional), lalu klik tombol Simpan Pengeluaran ini untuk menyimpannya.",
      },
      "open-history": {
        title: "Buka Riwayat Transaksi",
        body: "Keren! Sekarang mari klik tab Riwayat untuk memantau transaksi yang baru saja Anda catat.",
      },
      "tour-complete": {
        title: "Transaksi Tercatat!",
        body: "Hebat! Transaksi yang baru saja Anda input sudah terdaftar rapi paling atas di sini.",
        primaryCta: "Lanjut",
      },
      "advanced-features": {
        title: "Fitur Otomatisasi & Widget",
        body: "Gunakan juga fitur canggih lainnya:\n• Widget Layar Utama: Klik nominal banknote untuk mencatat secara instan tanpa buka aplikasi.\n• Baca Notifikasi Bank: Rekam otomatis pengeluaran dari SMS & push notification.\n• Scan Struk & Import CSV di halaman Dompet.",
        educationTitle: "Edukasi Otomatisasi",
        tabWidget: "Widget HP",
        tabNotif: "Auto-Notif",
        tabReceipt: "Pindai Struk",
        tabStreak: "Streak & Koin",
        slides: {
          widget: {
            title: "Widget Layar Utama (Android)",
            description: "Catat pengeluaran instan tanpa perlu membuka aplikasi. Cukup ketuk nominal pecahan uang langsung di homescreen HP Anda, kumpulkan totalnya, lalu klik OK untuk menyimpan."
          },
          notification: {
            title: "Sinkronisasi Notifikasi Otomatis",
            description: "Punya notifikasi M-Banking atau SMS transaksi masuk? Budget Flow membaca push notifikasi tersebut dan mencatat pengeluaran Anda secara otomatis di latar belakang."
          },
          receipt: {
            title: "Pindai Struk & Import CSV",
            description: "Malas mencatat satu per satu? Ambil foto struk belanja untuk dipindai otomatis oleh AI OCR, atau import riwayat mutasi lewat file CSV dari Dompet → Impor."
          },
          streak: {
            title: "Sistem Streak & Koin Harian",
            description: "Jaga streak Anda tetap menyala dengan rutin mencatat transaksi atau menandai Zero-Spend Day. Dapatkan +5 Koin jika pengeluaran harian Anda di bawah limit belanja aman. Tukarkan koin dengan Streak Freeze di Toko Settings sebagai pengaman di hari darurat!"
          }
        }
      }
    }
  },
  en: {
    common: {
      home: "Dashboard",
      plan: "Budget Plan",
      history: "Ledger",
      wallet: "Wallets",
      settings: "Settings",
      logout: "Log Out",
      cancel: "Cancel",
      save: "Save",
      confirm: "Confirm",
      edit: "Edit",
      delete: "Delete",
      loading: "Processing...",
      success: "Success",
      error: "Error",
      account: "Account & Settings",
      back: "Back",
      next: "Next",
      skip: "Skip",
      done: "Done",
      close: "Close",
      add: "Add New",
      record: "Log",
      today: "Today",
      total: "Total",
      estimated: "Estimated",
      notes: "Notes",
      actions: "Actions",
      saveChanges: "Save Changes",
    },
    settings: {
      title: "Settings",
      subtitle: "Customize the app to fit your style.",
      description: "Set account preferences, notification permissions, and export data.",
      accountSection: "Account",
      accountDesc: "Budget Flow Account",
      changePassword: "Change Password",
      changePasswordDesc: "Change your password for extra security.",
      changePasswordButton: "Open",
      logoutDesc: "Log out of your account anytime.",
      logoutButton: "Log Out",
      deleteAccount: "Delete Account",
      deleteAccountDesc: "Permanently delete your account and all data from our database.",
      deleteAccountButton: "Delete",
      preferencesSection: "Preferences",
      browserNotifications: "Browser Notifications",
      browserNotificationsActive: "Enabled – you'll receive budget and recurring reminders.",
      browserNotificationsBlocked: "Blocked – enable manually in browser settings (click 🔒 on address bar).",
      browserNotificationsDefault: "Allow notifications to receive budget & recurring expense alerts.",
      browserNotificationsUnsupported: "Notifications are not supported by this browser.",
      browserNotificationsBtn: "Enable",
      androidTracking: "Android Transaction Tracker",
      androidTrackingActive: "Access Active – transactions automatically monitored in the background from alerts/emails.",
      androidTrackingInactive: "Access Disabled – enable to let the app automatically record expenses from GoPay, SeaBank, and Gmail.",
      androidTrackingBtnActive: "Configure",
      androidTrackingBtnInactive: "Enable",
      testNotification: "Test Send Notification",
      testNotificationDesc: "Tap to test if the system push notifications are working.",
      testNotificationBtn: "Test",
      designPreview: "Design Preview (V2)",
      designPreviewDesc: "Try our new dark hybrid theme layout interface.",
      designPreviewBtn: "Open V2",
      viewTutorial: "Relaunch Tutorial",
      viewTutorialDesc: "Reopen the onboarding flow and show the starter checklist.",
      viewTutorialBtn: "Open",
      appPermissions: "App Permission Allowlist",
      appPermissionsDesc: "Financial applications to monitor notifications for. OTPs and verification codes are filtered out automatically.",
      appPermissionsFooter: "Active when Budget Flow runs as an Android APK.",
      financialData: "Financial Data",
      exportCSV: "Export Transactions (CSV)",
      exportCSVDesc: "Download a copy of your expenses to share or double check.",
      exportCSVBtn: "Export",
      aboutApp: "About Application",
      appVersion: "App Version",
      language: "App Language",
      languageDesc: "Change the application interface language.",
      languageIndo: "Indonesian",
      languageEng: "English",
      modalChangePasswordTitle: "Change Password",
      modalChangePasswordSub: "Create a secure new password for your account",
      modalNewPasswordLabel: "New Password",
      modalNewPasswordPlaceholder: "Minimum 6 characters",
      modalConfirmPasswordLabel: "Confirm New Password",
      modalConfirmPasswordPlaceholder: "Repeat new password",
      modalLogoutTitle: "Log out of Account?",
      modalLogoutDesc: "Are you sure you want to log out? You will need to sign back in to access your transactions.",
      modalLogoutConfirm: "Log Out Now",
      modalDeleteTitle: "Permanently Delete Account?",
      modalDeleteDesc: "Are you sure you want to delete your account? All your categories, wallets, and transactions will be gone for good.",
      modalDeleteConfirm: "Delete Permanently",
    },
    home: {
      dailySpending: "FINANCIAL SUMMARY",
      safeToSpendToday: "SAFE-TO-SPEND TODAY",
      safeToSpendDesc: "How much you can spend today without touching your savings or upcoming bills.",
      cleanCash: "CLEAN CASH",
      upcomingBills: "UPCOMING BILLS",
      daysToPayday: "DAYS TO PAYDAY",
      daysToPaydaySuffix: "days",
      dailyLimit: "DAILY USAGE",
      dailyLimitOver: "LIMIT EXCEEDED!",
      dailyLimitNormal: "Daily safe limit: Rp {limit}",
      overspendMessage: "Overspent by Rp {amount}! Spend less tomorrow and check today's transactions.",
      progressPlan: "PLAN BUDGET PROGRESS NAMA",
      planIncome: "Estimated Income",
      planExpense: "Total Expense",
      planSavings: "Plan Remaining",
      categorySpending: "Plan Budget Usage",
      todayTransactions: "TODAY'S EXPENSES",
      noTransactionsToday: "No expenses recorded today. Tap the + button below to log one!",
      checklistTitle: "Starter Checklist",
      checklistSubtitle: "Complete these steps to make your daily Safe-To-Spend calculation highly accurate.",
      checklistIntro: "Introductory Steps",
      checklistDismissSuccess: "Onboarding checklist hidden. You can show it again in Settings.",
      checklistAllDone: "Awesome! You have completed all setup steps.",
      checklistNotDone: "Complete these steps to make your daily Safe-To-Spend calculation highly accurate.",
      checklistProgress: "Setup Progress",
      checklistCompletedPercent: "{percent}% Completed",
      checklistDismissTooltip: "Hide Checklist",
      step1Title: "Link Your First Wallet",
      step1Desc: "Add your cash, bank account, or e-wallet to track your balance.",
      step1Action: "Add Wallet",
      step2Title: "Add Planned Income",
      step2Desc: "Set your estimated monthly payday or income source.",
      step2Action: "Set Income",
      step3Title: "Set Category Budgets",
      step3Desc: "Allocate spending limits for categories like Food or Transport.",
      step3Action: "Set Budget",
      step4Title: "Log Your First Expense",
      step4Desc: "Start logging transactions manually or auto-track via notifications.",
      step4Action: "Record Now",
      step5Title: "Check & Reconcile Balance",
      step5Desc: "Adjust your wallet balance so it matches your real-life money.",
      step5Action: "Update Balance",
      checklistDone: "Completed",
      overview: "Overview",
      analytics: "Analytics",
      safeToSpendLeft: "You still have Rp {amount} remaining for today's budget.",
      spent: "spent",
      paydayModalTitle: "Change Payday Date",
      paydayModalSub: "Adjust your monthly payday cycle for Safe-To-Spend calculations.",
      paydayLabel: "Payday Date (1 - 31)",
      paydayDesc: "Your daily safe-to-spend limit will be calculated based on the days left until payday.",
      paydayError: "Payday must be between 1 and 31.",
      paydaySuccess: "Payday cycle set to the {day} of the month.",
      loadingDashboard: "Loading Dashboard...",
      dashboardError: "Failed to load dashboard data.",
      permissionTitle: "Enable Auto-Track Transactions",
      permissionDesc: "Allow notification access so Budget Flow can automatically log expenses from SMS or e-wallet alerts.",
      permissionBtn: "Enable Now",
      permissionError: "Failed to open settings.",
      avgDaily: "Daily Average",
      totalTransactions: "Total Transactions",
      planUsage: "Plan Usage",
      qrisFreq: "QRIS Frequency",
      times: "times",
      dailySpendingTrend: "Daily Spending Trend",
      expenses: "Expenses",
      day: "Day",
      noTransactionsThisMonth: "No transaction data for this month.",
      categorySpendingShare: "Category Spending Breakdown",
      noCategorySpending: "No category spending recorded yet.",
      topSpendingCategories: "Top Spending Categories",
      smartInsights: "Smart Insights",
      qrisBurnRateTitle: "💡 QRIS Burn Rate:",
      qrisBurnRateText: "Your biggest spending is in the {category} category. Try limiting e-wallet QRIS payments to stay in control.",
      qrisBurnRateEmpty: "E-wallet transaction patterns cannot be analyzed yet. Please import transaction data first.",
      avgSpendingTitle: "📈 Daily spending average:",
      avgSpendingText: "per day. Keep it under Rp {limit} to potentially save Rp {savings} this month!",
      quickActionsTitle: "Quick Actions",
      quickActionsSubtitle: "Quick shortcuts to log and manage transactions",
      actionUploadReceiptTitle: "Upload Transaction Receipt",
      actionUploadReceiptDesc: "Record expenses via photo/scan of receipts",
      actionScreenshotBalanceTitle: "Update Balance from Screenshot",
      actionScreenshotBalanceDesc: "Adjust e-wallet balances via screenshot image",
      actionImportCsvTitle: "Import Transaction CSV",
      actionImportCsvDesc: "Upload bank transaction history files all at once"
    },
    wallets: {
      firstRunWalletTitle: "Manage Your Wallets",
      firstRunWalletDesc: "Track cash, bank accounts, or e-wallets. The app splits your money into Confirmed Balance (last verified amount) and Estimated Balance (calculated changes since verification).",
      title: "Wallets List",
      subtitle: "Manage confirmed vs estimated balances with auto-ingestion.",
      addWallet: "Add Wallet",
      importStatement: "Import Account",
      estimatedBalance: "Estimated Balance",
      confirmedBalance: "Confirmed Balance",
      confirmedBalanceDesc: "Last synchronized from bank/e-wallet notification alerts.",
      daysAgo: "{days} days ago",
      justNow: "just now",
      needConfirmation: "Needs Confirmation",
      gapDifference: "Estimated difference: Rp {gap}",
      resolveGap: "Resolve Gap",
      recentTransactions: "Recent Transactions",
      noTransactions: "No transactions in this wallet yet.",
      importCSV: "Import CSV",
      importCSVDesc: "Upload transaction records from a banking CSV file.",
      scanReceipt: "Scan Receipt (OCR)",
      scanReceiptDesc: "Take a photo or upload a receipt to auto-record expenses.",
      addWalletTitle: "Add New Wallet",
      walletName: "Wallet Name",
      walletNamePlaceholder: "Example: BCA, GoPay, Cash",
      walletInitialBalance: "Initial Balance (Rp)",
      walletType: "Wallet Type",
      walletTypeBank: "Bank Account",
      walletTypeEWallet: "Digital Wallet (E-Wallet)",
      walletTypeCash: "Cash / Cash",
      walletTypeOther: "Other",
      saveWallet: "Save Wallet",
      scanReceiptTitle: "Scan Receipt AI OCR",
      scanReceiptSubtitle: "Scan receipt details automatically for fast logging",
      selectReceiptImage: "Select Receipt Photo",
      processingOCR: "AI is scanning receipt details... Please wait.",
      ocrResult: "Scan Result",
      ocrTotalAmount: "Total Amount Detected",
      ocrMerchant: "Merchant Detected",
      ocrNote: "Auto Note",
      ocrAddToHistory: "Log as Expense",
      importCsvTitle: "Import Statements (CSV)",
      importCsvSubtitle: "Upload CSV statements downloaded from your mobile banking",
      selectCsvFile: "Select CSV File",
      importCsvColumns: "Map CSV Columns",
      importCsvBtn: "Start Import",
      labelNeverConfirmed: "Never",
      btnGapAnalysis: "Gap Analysis",
      btnAdjustBalance: "Adjust Balance",
      btnRegisterNew: "Add New Wallet",
      descRegisterNew: "Add a new bank account or e-wallet you own",
      formWalletName: "Wallet Name",
      formWalletNamePlaceholder: "e.g. BCA, GoPay, Cash",
      formWalletType: "Wallet Type",
      formProvider: "Provider (Optional)",
      formProviderPlaceholder: "e.g. Mandiri, GoPay, OVO",
      formInitialBalance: "Initial Balance (Rp)",
      btnSaving: "Saving...",
      loadingWallets: "Loading Wallets..."
    },
    budget: {
      headerTag: "Budget Plan",
      title: "Plans & Categories",
      subtitle: "Set up your category budgets, income sources, and recurring bills.",
      monthlyOverview: "Monthly Overview",
      totalPlanned: "Total Budget",
      totalSpent: "Total Spent",
      remainingPlanned: "Remaining Budget",
      addCategory: "Add Category",
      manageRecurring: "Manage Recurring",
      statusHealthy: "Healthy",
      statusWatch: "Warning",
      statusOver: "Budget Exceeded",
      categoryName: "Category Name",
      categoryBudget: "Monthly Budget",
      recurringExpenses: "Recurring Bills",
      addRecurring: "Add Bill",
      recurringName: "Bill Name",
      recurringAmount: "Bill Amount",
      recurringPeriod: "Period",
      recurringPeriodMonthly: "Monthly",
      recurringPeriodWeekly: "Weekly",
      recurringDueDate: "Due Date",
      recurringDueDateSuffix: "every {date} of the month",
      recurringAutoSync: "Auto-Synchronization",
      categoryManagement: "Manage Category Budgets",
      addCategoryTitle: "Add Budget Category",
      editCategoryTitle: "Edit Budget Category",
      saveCategory: "Save Category",
      deleteCategoryConfirm: "Are you sure you want to delete this category? All transactions under it will be moved to 'Others'.",
      tabCategory: "Category Budgets",
      tabCategoryMobile: "Categories",
      tabIncome: "Income Sources",
      tabIncomeMobile: "Income",
      tabRecurring: "Recurring Bills",
      tabRecurringMobile: "Bills",
      utilization: "Total Usage",
      statusOnTrack: "On Track",
      statusUnder: "Under Budget",
      recsTitle: "Recommendations",
      recsCollapse: "Show Less",
      recsExpand: "Show All",
      detailsTitle: "Category Details",
      detailsDesc: "Compare your budget and actual spending per category.",
      activeCategories: "{count} active categories",
      emptyCategoriesTitle: "No Budget Categories Yet",
      emptyCategoriesDesc: "Add categories (e.g. Food, Entertainment) with monthly budget limits.",
      emptyCategoriesBtn: "Add First Category",
      labelTransactionsCount: "{count} transactions",
      labelBudget: "Budget",
      labelSpent: "Spent",
      labelRemaining: "Remaining",
      labelOver: "Over",
      incomeTitle: "Income Sources",
      incomeDesc: "Manage your monthly or weekly income sources.",
      incomeAddBtn: "Add Income",
      incomeEmptyTitle: "No Planned Income Yet",
      incomeEmptyDesc: "Add income sources (salary, business, etc.) to calculate Safe-To-Spend accurately.",
      incomeEmptyBtn: "Add First Income",
      recurringTitle: "Recurring Bills",
      recurringDesc: "{count} recurring bills registered.",
      recurringSyncBtn: "Sync",
      recurringExportBtn: "Export .ics",
      recurringAddBtn: "Add Bill",
      recurringEmptyTitle: "No Recurring Bills Yet",
      recurringEmptyDesc: "Add recurring bills (rent, electricity, wifi) to simplify tracking essential expenses.",
      recurringEmptyBtn: "Add First Bill",
      recurringEveryDate: "Every {day} of the month",
      recurringEveryFreq: "Every {freq}",
      firstRunPlanTitle: "Manage Category Budgets",
      firstRunPlanDesc: "Compare your monthly budget limits against actual spending per category. You'll also get tips if you start overspending.",
      firstRunIncomeTitle: "Planned Income Sources",
      firstRunIncomeDesc: "Plan your estimated income sources here. These numbers are used to dynamically calculate your daily Safe-To-Spend limit on the Home screen.",
      firstRunRecurringTitle: "Recurring Bills & Subscriptions",
      firstRunRecurringDesc: "Track recurring bills (like rent, internet, utilities). Sync them directly to your monthly expenses with the Sync button."
    },
    history: {
      headerTag: "Ledger",
      title: "Transaction History",
      subtitle: "Review and adjust all your expense and income records.",
      searchPlaceholder: "Search transactions...",
      filterCategory: "All Categories",
      filterWallet: "All Wallets",
      filterMonth: "All Months",
      noTransactions: "No transactions matched your selected filters.",
      totalExpenses: "Total Expenses",
      totalIncome: "Total Income",
      transactionDetails: "Transaction Details",
      dateLabel: "Date",
      amountLabel: "Amount",
      categoryLabel: "Category",
      walletLabel: "Wallet / Account",
      noteLabel: "Notes",
      deleteTransactionConfirm: "Are you sure you want to delete this transaction?",
      emptyTitle: "No Transactions Yet",
      emptyDesc: "Log your first expense or income to see your history here.",
      emptyBtn: "Log First Transaction",
      dateToday: "Today",
      dateYesterday: "Yesterday",
      txAutoNotif: "Auto Notification",
      txManual: "Manual Transaction",
      labelNotifDetail: "Notification Details:",
      labelNote: "Notes:",
      noNote: "No notes",
      btnEditNote: "Edit",
      btnCancel: "Cancel",
      btnSave: "Save",
      labelCategory: "Category:",
      btnSelectCategory: "+ Select Category",
      btnNoCategory: "— No Category —",
      btnDelete: "Delete",
      loadingLedger: "Loading Ledger...",
      deleteConfirm: "Are you sure you want to delete this transaction?",
      firstRunHistoryTitle: "Review Transaction History",
      firstRunHistoryDesc: "This ledger lets you monitor past expenses and income. You can search transactions, add quick notes, or update categories."
    },
    transactionModal: {
      expenseTitle: "Log Expense",
      incomeTitle: "Log Income",
      incomeEditTitle: "Edit Income",
      directionNewTx: "New Transaction",
      labelAmount: "Amount (Rp)",
      labelCategory: "Category",
      labelCategoryPlaceholder: "Select Category",
      labelWallet: "Wallet / Account (Optional)",
      labelWalletStorage: "Wallet / Account (Storage)",
      labelWalletPlaceholder: "— Cash / Manual (No Wallet) —",
      labelDate: "Date",
      labelDatePlaceholder: "Select Date",
      labelNote: "Notes / Description",
      labelNoteExpensePlaceholder: "Lunch, coffee, etc...",
      labelNoteIncomePlaceholder: "Salary, freelance, etc...",
      btnSaveExpense: "Save Expense",
      btnSaveIncome: "Save Income",
      btnSaveChange: "Save Changes",
      msgInvalidAmount: "Invalid amount.",
      msgInvalidAmountIncome: "Invalid amount.",
      msgSelectCategory: "Select a category.",
      msgSelectSource: "Select an income source.",
      msgSaveSuccessExpense: "Expense saved successfully.",
      msgSaveSuccessIncome: "Income saved successfully.",
      msgSaveSuccessIncomeUpdate: "Income updated successfully.",
      newTransaction: "New Transaction",
      addExpenseTitle: "Add Expense",
      addIncomeTitle: "Add Income",
      selectCategoryPlaceholder: "Select Category",
      manualCashNoWallet: "— Cash / Manual (No Wallet) —",
      selectDatePlaceholder: "Select Date",
      notePlaceholderExpense: "Lunch, coffee, etc...",
      notePlaceholderIncome: "Salary, freelance, etc...",
      btnSaving: "Saving...",
      labelIncomeSource: "Income Source",
      selectSourcePlaceholder: "Select Source",
      labelWalletDeposit: "Deposit Wallet (Optional)"
    },
    tour: {
      "welcome-home": {
        title: "Welcome to Your Dashboard",
        body: "Monitor your Safe-To-Spend limit, daily use bounds, and monthly plans right from here.",
        primaryCta: "Start Logging",
      },
      "open-record-sheet": {
        title: "Click Record Button",
        body: "Tap the + button in the navigation center (or 'Add New' in the sidebar) to open the transaction logger.",
      },
      "choose-expense": {
        title: "Choose Expense",
        body: "Select the Expense option to manually record outgoing money.",
      },
      "input-amount": {
        title: "Enter Amount",
        body: "Type the transaction amount in this field (e.g. 15,000).",
        primaryCta: "Continue",
      },
      "save-expense": {
        title: "Save Transaction",
        body: "Input the amount above, choose a category (optional), and click Save Expense to store it.",
      },
      "open-history": {
        title: "Open Transaction History",
        body: "Great! Let's click the History tab to review the transaction you just logged.",
      },
      "tour-complete": {
        title: "Transaction Logged!",
        body: "Excellent! The transaction you entered is now listed at the very top of your history list.",
        primaryCta: "Continue",
      },
      "advanced-features": {
        title: "Automation & Widgets",
        body: "Take advantage of these advanced capabilities:\n• Homescreen Widget: Tap money banknotes on your home screen to record expenses instantly.\n• Auto Bank Sync: Read push notifications or SMS to record costs in the background.\n• OCR Scanner & CSV Import under the Wallets screen.",
        educationTitle: "Automation Education",
        tabWidget: "Phone Widget",
        tabNotif: "Auto-Notif",
        tabReceipt: "Scan Receipt",
        tabStreak: "Streak & Coins",
        slides: {
          widget: {
            title: "Home Screen Widget (Android)",
            description: "Log expenses instantly without opening the app. Simply tap the cash banknotes directly on your phone's home screen, aggregate the total, and tap OK to save."
          },
          notification: {
            title: "Automatic Notification Sync",
            description: "Have banking app notifications or transaction SMS alerts? Budget Flow parses incoming push notifications and automatically records your spending in the background."
          },
          receipt: {
            title: "Receipt Scanner & CSV Import",
            description: "Hate logging one by one? Take a photo of your receipt to scan automatically with AI OCR, or import account histories via a CSV file under Wallets → Import."
          },
          streak: {
            title: "Streak & Coins System",
            description: "Keep your daily streak alive by recording transactions or confirming a Zero-Spend Day. Earn +5 Coins when your daily spending stays under your Safe-To-Spend limit. Redeem coins for a Streak Freeze in the Settings Shop as an emergency backup!"
          }
        }
      }
    }
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = window.localStorage.getItem("bf_language");
      if (saved === "en" || saved === "id") return saved;
    }
    return "id"; // Default: Indonesian
  });

  const setLang = (nextLang: Language) => {
    setLangState(nextLang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("bf_language", nextLang);
    }
  };

  const t = (path: string, defaultValue?: string): string => {
    const keys = path.split(".");
    let current: any = translations[lang];

    for (const key of keys) {
      if (current && typeof current === "object" && key in current) {
        current = current[key];
      } else {
        return defaultValue !== undefined ? defaultValue : path;
      }
    }

    return typeof current === "string" ? current : (defaultValue !== undefined ? defaultValue : path);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
