-- =========================================================================
-- BUDGET FLOW - FULL SCHEMA INITIALIZATION
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)
--
-- This script contains the complete, consolidated schema definition for 
-- all tables, indexes, triggers, and RLS (Row Level Security) policies.
-- =========================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── 1. BUDGET CATEGORIES ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS budget_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  budget_amount NUMERIC NOT NULL DEFAULT 0 CHECK (budget_amount >= 0),
  color TEXT NOT NULL DEFAULT '#FF6B6B',
  priority INTEGER NOT NULL DEFAULT 3 CHECK (priority >= 1 AND priority <= 5),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE budget_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own budget categories"
  ON budget_categories FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_budget_categories_user_id ON budget_categories(user_id);

-- ── 2. INCOME SOURCES ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS income_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source_name TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0 CHECK (amount >= 0),
  frequency TEXT NOT NULL DEFAULT 'monthly',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE income_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own income sources"
  ON income_sources FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_income_sources_user_id ON income_sources(user_id);

-- ── 3. RECURRING EXPENSES ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS recurring_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES budget_categories(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  note TEXT,
  frequency TEXT NOT NULL DEFAULT 'monthly' CHECK (frequency IN ('daily', 'weekly', 'monthly')),
  day_of_month INTEGER CHECK (day_of_month >= 1 AND day_of_month <= 31),
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE recurring_expenses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own recurring expenses"
  ON recurring_expenses FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_recurring_expenses_user_id ON recurring_expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_recurring_expenses_category_id ON recurring_expenses(category_id);

-- ── 4. MONTHLY PLANS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS monthly_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  month TEXT NOT NULL CHECK (month ~ '^\d{4}-\d{2}$'),
  income NUMERIC NOT NULL DEFAULT 0 CHECK (income >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, month)
);

ALTER TABLE monthly_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own monthly plans"
  ON monthly_plans FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_monthly_plans_user_month ON monthly_plans(user_id, month);

-- ── 5. WALLETS ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wallets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'other' CHECK (type IN ('bank', 'ewallet', 'cash', 'other')),
  provider TEXT,
  confirmed_balance NUMERIC NOT NULL DEFAULT 0,
  estimated_balance NUMERIC NOT NULL DEFAULT 0,
  last_confirmed_at TIMESTAMPTZ,
  confidence NUMERIC NOT NULL DEFAULT 1.0 CHECK (confidence >= 0 AND confidence <= 1),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own wallets"
  ON wallets FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_wallets_user_id ON wallets(user_id);

-- ── 6. WALLET TRANSACTIONS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  wallet_id UUID REFERENCES wallets(id) ON DELETE SET NULL,
  category_id BIGINT REFERENCES budget_categories(id) ON DELETE SET NULL,
  income_source_id UUID REFERENCES income_sources(id) ON DELETE SET NULL,
  recurring_expense_id BIGINT REFERENCES recurring_expenses(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  direction TEXT NOT NULL CHECK (direction IN ('in', 'out')),
  type TEXT NOT NULL DEFAULT 'expense' CHECK (type IN ('expense', 'income', 'transfer_out', 'transfer_in', 'adjustment')),
  category TEXT, -- legacy string category field
  merchant TEXT,
  note TEXT,
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('notification', 'screenshot', 'csv', 'receipt', 'manual', 'adjustment')),
  raw_text TEXT,
  confidence NUMERIC NOT NULL DEFAULT 1.0 CHECK (confidence >= 0 AND confidence <= 1),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_duplicate BOOLEAN NOT NULL DEFAULT false,
  matched_transaction_id UUID REFERENCES wallet_transactions(id) ON DELETE SET NULL
);

ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own wallet transactions"
  ON wallet_transactions FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_user_id ON wallet_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_wallet_id ON wallet_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_occurred_at ON wallet_transactions(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_category_id ON wallet_transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_income_source_id ON wallet_transactions(income_source_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_recurring_expense_id ON wallet_transactions(recurring_expense_id);

-- ── 7. BALANCE ADJUSTMENTS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS balance_adjustments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  wallet_id UUID NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
  previous_estimated_balance NUMERIC NOT NULL,
  new_confirmed_balance NUMERIC NOT NULL,
  difference NUMERIC NOT NULL,
  reason TEXT,
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'screenshot', 'csv')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE balance_adjustments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own balance adjustments"
  ON balance_adjustments FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_balance_adjustments_wallet_id ON balance_adjustments(wallet_id);

-- ── 8. NOTIFICATION ALLOWLIST ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notification_allowlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  package_name TEXT NOT NULL,
  app_name TEXT NOT NULL,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, package_name)
);

ALTER TABLE notification_allowlist ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own notification allowlist"
  ON notification_allowlist FOR ALL USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_notification_allowlist_user_pkg ON notification_allowlist(user_id, package_name);

-- ── 9. FUNCTIONS & TRIGGERS ─────────────────────────────────────────────

-- Trigger function: Update updated_at column automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to tables that need it
CREATE TRIGGER trg_budget_categories_updated_at BEFORE UPDATE ON budget_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_income_sources_updated_at BEFORE UPDATE ON income_sources FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_recurring_expenses_updated_at BEFORE UPDATE ON recurring_expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_monthly_plans_updated_at BEFORE UPDATE ON monthly_plans FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wallets_updated_at BEFORE UPDATE ON wallets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function: Recalculate wallet estimated_balance based on transactions
CREATE OR REPLACE FUNCTION recalculate_wallet_estimated_balance()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE wallets
  SET
    estimated_balance = confirmed_balance + COALESCE((
      SELECT
        SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END)
      FROM wallet_transactions
      WHERE wallet_id = COALESCE(NEW.wallet_id, OLD.wallet_id)
        AND user_id = COALESCE(NEW.user_id, OLD.user_id)
        AND is_duplicate = false
        AND (last_confirmed_at IS NULL OR occurred_at >= last_confirmed_at)
    ), 0),
    updated_at = now()
  WHERE id = COALESCE(NEW.wallet_id, OLD.wallet_id);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Apply recalc trigger to wallet_transactions
CREATE TRIGGER trg_recalc_balance_after_tx
AFTER INSERT OR UPDATE OR DELETE ON wallet_transactions
FOR EACH ROW EXECUTE FUNCTION recalculate_wallet_estimated_balance();

-- Function: delete current user (for account self-deletion)
CREATE OR REPLACE FUNCTION delete_user()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM auth.users WHERE id = auth.uid();
END;
$$;

-- Function: adjust wallet balance atomically
CREATE OR REPLACE FUNCTION adjust_wallet_balance(
  p_wallet_id UUID,
  p_new_balance NUMERIC,
  p_reason TEXT,
  p_source TEXT
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_old_balance NUMERIC;
BEGIN
  -- Fetch the current balance of the wallet
  SELECT estimated_balance INTO v_old_balance FROM wallets WHERE id = p_wallet_id AND user_id = auth.uid() FOR UPDATE;
  
  IF v_old_balance IS NULL THEN
    RAISE EXCEPTION 'Wallet not found or access denied';
  END IF;

  -- Log the balance adjustment
  INSERT INTO balance_adjustments (
    user_id,
    wallet_id,
    previous_estimated_balance,
    new_confirmed_balance,
    difference,
    reason,
    source
  ) VALUES (
    auth.uid(),
    p_wallet_id,
    v_old_balance,
    p_new_balance,
    p_new_balance - v_old_balance,
    p_reason,
    p_source
  );

  -- Update confirmed_balance and estimated_balance on the wallet
  UPDATE wallets
  SET 
    confirmed_balance = p_new_balance,
    estimated_balance = p_new_balance,
    last_confirmed_at = now(),
    confidence = 1.0
  WHERE id = p_wallet_id AND user_id = auth.uid();
END;
$$;
